table dAnim
	lineageTag: c9b7b42b-7f61-46e7-b06a-9236ba213df7

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 15ef0c77-ca70-439d-88aa-012a83b52e76
		summarizeBy: sum
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Animations
		dataType: string
		lineageTag: d1717d20-db93-4a08-b3d7-a853c80136c8
		summarizeBy: none
		sourceColumn: Animations
		sortByColumn: Id

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition dAnim = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQrPT0rKSVWK1YlWMgJygzMSsyE8YyDPJTEvGcIzAcmV5BcoxcYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t, #"Coluna 2" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", Int64.Type}, {"Coluna 2", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Coluna 2", "Animations"}, {"Coluna 1", "Id"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_ResultType = Table

