createOrReplace

	table dCalendario
		lineageTag: 975eebd0-a6b2-45fa-8081-99b5af10a4c5

		column Data
			dataType: dateTime
			formatString: Short Date
			lineageTag: 7e20387e-b16b-4332-85a8-641ef4f34fa8
			summarizeBy: none
			sourceColumn: Data

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column Ano
			dataType: int64
			formatString: 0
			lineageTag: 365aec16-8e6b-4439-b59a-fbb5ca1e6a4f
			summarizeBy: none
			sourceColumn: Ano

			annotation SummarizationSetBy = Automatic

		column Mes
			dataType: int64
			formatString: 0
			lineageTag: 4d2b88fa-a875-44a0-9b31-473b50f5cb51
			summarizeBy: none
			sourceColumn: Mes

			annotation SummarizationSetBy = Automatic

		column Dia
			dataType: int64
			formatString: 0
			lineageTag: 422b34fa-9044-47b0-abe8-b7c99885a8ba
			summarizeBy: none
			sourceColumn: Dia

			annotation SummarizationSetBy = Automatic

		column Trimestre
			dataType: string
			lineageTag: b4570177-6cc1-4d91-ba7a-a0d022d2906d
			summarizeBy: none
			sourceColumn: Trimestre

			annotation SummarizationSetBy = Automatic

		column DiaUtil
			dataType: int64
			formatString: 0
			lineageTag: f9e9abda-7397-4e61-9bce-7c83418b8a65
			summarizeBy: none
			sourceColumn: DiaUtil

			annotation SummarizationSetBy = Automatic

		column AnoMes
			dataType: string
			lineageTag: 653c6622-b22e-47c7-8d65-a64c90a42c82
			summarizeBy: none
			sourceColumn: AnoMes

			annotation SummarizationSetBy = Automatic

		column DiasUteisNoMes
			dataType: int64
			formatString: 0
			lineageTag: 2c1fede8-7402-4ad0-916a-d920369715e9
			summarizeBy: none
			sourceColumn: DiasUteisNoMes

			annotation SummarizationSetBy = Automatic

		partition dCalendario = m
			mode: import
			source = ```
					let
					    Fonte = #date(2012, 1, 1),
					    ListaDeDatas = List.Dates(
					        Fonte,
					        Number.From(DateTime.LocalNow()) - Number.From(Fonte),
					        #duration(1, 0, 0, 0)
					    ),
					    ListaAnoMes = List.Transform(ListaDeDatas, each [Data = _, Ano = Date.Year(_), Mes = Date.Month(_), Dia = Date.Day(_), Trimestre = Date.QuarterOfYear(_)]),
					    TabelaAnoMes = Table.FromRecords(ListaAnoMes),
					    TabelaComDiaUtil = Table.AddColumn(TabelaAnoMes, "DiaUtil", each if Date.DayOfWeek([Data], Day.Monday) < 5 then 1 else 0),
					    TabelaComAnoMes = Table.AddColumn(TabelaComDiaUtil, "AnoMes", each Text.From([Ano]) & "-" & Text.PadStart(Text.From([Mes]), 2, "0")),
					    TabelaComDiasUteisNoMes = Table.AddColumn(TabelaComAnoMes, "DiasUteisNoMes", each 
					        let
					            PrimeiroDiaDoMes = #date(Date.Year([Data]), Date.Month([Data]), 1),
					            UltimoDiaDoMes = Date.EndOfMonth([Data]),
					            ListaDiasNoMes = List.Dates(PrimeiroDiaDoMes, Duration.Days(UltimoDiaDoMes - PrimeiroDiaDoMes) + 1, #duration(1, 0, 0, 0)),
					            DiasUteis = List.Select(ListaDiasNoMes, each Date.DayOfWeek(_, Day.Monday) < 5)
					        in
					            List.Count(DiasUteis)
					    ),
					    #"Tipo Alterado" = Table.TransformColumnTypes(TabelaComDiasUteisNoMes, {{"Data", type date}, {"Ano", Int64.Type}, {"Mes", Int64.Type}, {"Dia", Int64.Type}, {"DiaUtil", Int64.Type}, {"DiasUteisNoMes", Int64.Type}})
					in
					    #"Tipo Alterado"
					```

		annotation PBI_NavigationStepName = Navegação

		annotation PBI_ResultType = Table

